on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: bookdown

jobs:
  bookdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
          use-public-rspm: true
      
      - name: Install dependencies
        run: |
          sudo apt -y install libcurl4-openssl-dev
          sudo apt -y install libharfbuzz-dev
          sudo apt -y install libfribidi-dev
          sudo apt -y install libudunits2-dev
          sudo apt -y install libgdal-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev
      
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      
      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
      
      - name: Build site
        run: bookdown::render_book("index.Rmd", quiet = TRUE)
        shell: Rscript {0}
      
      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _book
